export const StoreProducts = [
  {
    id:1,
    name:'Abon Sapi',
    img: "assets/Abon Sapi.png",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Daging Sapi",
    price: "18.000",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:2,
    name:'Astor Coklat',
    img: "assets/astorcoklat.png",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Coklat",
    price: "8.000",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:3,
    name:'Astor Vanilla',
    img: "assets/astor vanilla.png",
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Vanilla",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:4,
    name:'Biskuit Game Rose',
    img: "assets/gamerose.png",
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Manis Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:5,
    name:'Biskuit Bola Pelangi',
    img: "assets/biskuitbolapelangi.png",
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Manis Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:6,
    name:'Bagelan Butter Vanilla',
    img: "assets/bagelan.png",
    price: "11.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Vanilla Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:7,
    name:'Jagung Marning',
    img: "assets/jagungmarning.png",
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 200,
    taste:"Gurih Pedas Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:8,
    name:'Kacang Atom',
    img: "assets/kacang atom.png",
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:9,
    name:'Kacang Bawang',
    img: '../assets/kacang bawang.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet,consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Bawang",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:10,
    name:'Kacang Kedelai',
    img: '../assets/Kacang Kedelai.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 200,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:11,
    name:'Kacang Koro ',
    img: '../assets/kacang koro.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:12,
    name:'Kacang Kulit Sangrai',
    img: '../assets/kacang sangrai.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:13,
    name:'Kacang Thailand',
    img: '../assets/kacang thailand.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Pedas Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:14,
    name:'Kacang Polong',
    img: '../assets/kacang polong.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 200,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:15,
    name:'Kacang Polong Manis',
    img: '../assets/kacang polong manis.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 200,
    taste:"Gurih Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:16,
    name:'Kacang Telur Medan',
    img: '../assets/kacang telur medan.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:17,
    name:'Kacang Mix',
    img: '../assets/kacang mix.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 200,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:18,
    name:'Keripik Singkong Balado',
    img: '../assets/singkong balado.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Balado",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:19,
    name:'Keripik Singkong Keju',
    img: '../assets/singkong keju.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Keju",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:20,
    name:'Kerupuk Baso Tenggiri',
    img: '../assets/kerupukbaso.png',
    price: "13.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Ikan Tenggiri",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:21,
    name:'Keripik Bawang',
    img: '../assets/keripikbawang.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Bawang",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:22,
    name:'Keripik Pisang Asin',
    img: '../assets/keripikpisangasin.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:23,
    name:'Keripik Tempe Asin',
    img: '../assets/keripik tempe asin.png',
    price: "12.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:24,
    name:'Kuping Gajah',
    img: '../assets/kuping gajah.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:25,
    name:'Kwaci',
    img: '../assets/kwaci.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:26,
    name:'Makaroni Rujak',
    img: '../assets/makaroni rujak.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Pedas Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:27,
    name:'Makaroni Asin',
    img: '../assets/makaroniasin.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Gurih Asin",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:28,
    name:'Marie Wijen',
    img: '../assets/mariewijen.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Manis Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:29,
    name:'Potato Stik Barbeque',
    img: '../assets/potatobbq.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Barbeque",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:30,
    name:'Samosa Ebi',
    img: '../assets/samosa ebi.png',
    price: "10.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Udang Ebi",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:31,
    name:'Sumpia Ebi',
    img: '../assets/sumpia ebi.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Udang Ebi",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:32,
    name:'Soes Coklat',
    img: '../assets/soes kering coklat.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Coklat Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:33,
    name:'Stik Balado',
    img: '../assets/stik balado.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 150,
    taste:"Balado",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:34,
    name:'Stik Keju',
    img: '../assets/stik keju.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Keju",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:35,
    name:'Telur Gabus Keju',
    img: '../assets/telur gabus keju.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Gurih Keju",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:36,
    name:'Tortilla Balado Pedas',
    img: '../assets/Tortilla Balado.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Balado Pedas",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:37,
    name:'Tortilla Jagung Barbeque',
    img: '../assets/Tortilla Jagung Barbeque.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Jagung Barbeque",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:38,
    name:'Twis Jagung Barbeque',
    img: '../assets/twis jagung barbeque.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Jagung Barbeque",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:39,
    name:'Twis Jagung Panggang',
    img: '../assets/twis jagung panggang.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Jagung Panggang",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:40,
    name:'Pisang Sale Manis',
    img: '../assets/pisangsale.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Manis Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:41,
    name:'Kembang Goyang',
    img: '../assets/kembanggoyang.png',
    price: "10.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:42,
    name:'Emping Pedas Manis',
    img: '../assets/empingpedas.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Pedas Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:43,
    name:'Wafer Bola Chocolate',
    img: '../assets/waferchoco.png',
    price: "13.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Coklat Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:44,
    name:'Permen Susu',
    img: '../assets/permen-susu.png',
    price: "10.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Susu Manis",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id:45,
    name:'Jelly Jeruk Mandarin',
    img: '../assets/jellyjerukmandarin.png',
    price: "8.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 100,
    taste:"Jeruk Mandarin",
    inCart: false,
    count: 0,
    total: 0
  },

]


export const DetailProducts = [
  {
    id:1,
    name:'Kacang Atom',
    img: "assets/kacang atom.png",
    price: "160.000",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    weight: 200,
    taste:"Gurih",
    inCart: false,
    count: 0,
    total: 0
  },
]
